# Generated by Django 4.2 on 2023-04-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konfigurator',
            old_name='name',
            new_name='car',
        ),
    ]
