# Generated by Django 4.2 on 2023-05-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_dilery_alter_car_price_alter_konfigurator_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extiyot_qisimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_extiyotqisimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('extiyot_qisimlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_extiyot_qisimlar', to='app.extiyot_qisimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Order_extiyotqisimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('total_price', models.FloatField()),
                ('sub_extiyotqisimlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_extiyotqisimlar', to='app.sub_extiyotqisimlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_extiyotqisimlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('total_price', models.FloatField()),
                ('konfiguratsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.konfigurator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_car', to='app.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_extiyotqisimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_extiyotqisimlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_extiyotqisimlar', to='app.sub_extiyotqisimlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_extiyotqisimlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('konfiguratsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.konfigurator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
