# Generated by Django 4.2 on 2023-05-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_extiyot_qisimlar_sub_extiyotqisimlar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_extiyotqisimlar',
            name='price',
        ),
    ]
