# Generated by Django 4.2 on 2023-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sub_extiyotqisimlar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_car',
            name='dislike',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='like_car',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
