# Generated by Django 4.2 on 2023-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sub_extiyotqisimlar_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilery',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
